apiVersion: v1
kind: Secret
metadata:
  name: llm-env
type: Opaque
stringData:
  REDIS_HOST: "rd2"
  BACKEND_URL: "http://backend:8000/result/llm_callback/"
  ASYNC_JOB_MAX_RETRIES: "4"
  ASYNC_JOB_RETRY_DELAY: "10"
  ASYNC_JOB_TIMEOUT: "1800"
  MARK_LEFTOVER_RESULT_KEY: "leftover"
  MARK_DANGLING_RESULT_KEY: "dangling"
