substitutions:
  _COMMIT_SHA: $COMMIT_SHA
  _REGION:     "europe-west1"

steps:
  # A) Install & basic checks
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'lint']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']

  # B) Dependency vulnerability scan
  - name: 'gcr.io/cloud-builders/npm'
    args: ['audit', '--audit-level=high']

  # C) (Optional) Snyk SAST scan
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        export SNYK_TOKEN="$(gcloud secrets versions access latest --secret=snyk-token)"
        npm install -g snyk
        snyk test --severity-threshold=high

  # D) Build & tag container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/frontend/study-buddy-frontend:latest',
        '-t',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/frontend/study-buddy-frontend:${_COMMIT_SHA}',
        '.'
      ]

  # E) Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/frontend/study-buddy-frontend:latest'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/frontend/study-buddy-frontend:${_COMMIT_SHA}'
      ]

  # F) Trivy vulnerability scan of the image
  - name: 'aquasec/trivy:latest'
    args:
      [
        'image',
        '--exit-code', '1',
        '--severity',   'HIGH,CRITICAL',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/frontend/study-buddy-frontend:latest'
      ]

  # G) (Optional) Preview deploy for DAST
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy sb-frontend-preview \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/frontend/study-buddy-frontend:latest \
          --region ${_REGION} --platform managed --quiet
        PREVIEW_URL=$(gcloud run services describe sb-frontend-preview \
          --region ${_REGION} --platform managed \
          --format="value(status.url)")
        echo "Preview URL: $PREVIEW_URL"

  # H) (Optional) OWASP ZAP baseline scan
  - name: 'owasp/zap2docker-stable'
    entrypoint: zap-baseline.py
    args:
      [
        '-t', '$PREVIEW_URL',
        '-r', 'zap_report.html',
        '-m', 'medium'
      ]

  # I) Deploy to production Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'study-buddy-frontend',
        '--image',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/frontend/study-buddy-frontend:latest',
        '--region',
        '${_REGION}',
        '--platform',
        'managed',
        '--quiet'
      ]

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/frontend/study-buddy-frontend:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/frontend/study-buddy-frontend:${_COMMIT_SHA}'

timeout: '1800s'
