apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-celery
  labels:
    app: backend-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-celery
  template:
    metadata:
      labels:
        app: backend-celery
    spec:
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc

      containers:
        - name: celery
          image: europe-west1-docker.pkg.dev/gruppo-11/microservice-docker-repo/backend:latest
          command: ["/bin/sh", "-c"]
          args:
            - >
              celery -A study worker -l info
          envFrom:
            - secretRef:
                name: backend-env
          volumeMounts:
            - name: staticfiles
              mountPath: /app/staticfiles
            - name: media
              mountPath: /app/media
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
