apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc

      containers:
        - name: backend
          image: europe-west1-docker.pkg.dev/gruppo-11/microservice-docker-repo/backend:latest
          envFrom:
            - secretRef:
                name: backend-env
          ports:
            - containerPort: 8000
          command: ["/bin/sh", "-c"]
          args:
            - >
              python /app/manage.py collectstatic --noinput &&
              python /app/manage.py migrate &&
              python /app/manage.py init_admin &&
              daphne -b 0.0.0.0 -p 8000 study.asgi:application

          volumeMounts:
            - name: staticfiles
              mountPath: /app/staticfiles
            - name: media
              mountPath: /app/media

          # Should be adjusted later
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
