# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nginx
  labels:
    app: backend-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-nginx
  template:
    metadata:
      labels:
        app: backend-nginx
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc

      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: staticfiles
              mountPath: /app/staticfiles
              readOnly: true
            - name: media
              mountPath: /app/media
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
