apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer # 👈 This is the key change
  loadBalancerIP: 34.140.192.73
  selector:
    app: backend-nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
