import './globals.css';
import { ReactNode } from 'react';
import type { Metadata } from 'next'; // Import the Metadata type
import { ThemeRegistry } from '@/context/ThemeContext';
import Navbar from '../components/Navbar';

// This metadata object defines the content for your <head> tag
export const metadata: Metadata = {
  title: {
    template: '%s | Study Buddy', // Allows pages to set their own title
    default: 'Study Buddy',      // The default title for your site
  },
  description: 'Your ultimate companion for organizing notes and acing exams.',
  icons: {
    icon: '/logo.ico', // Make sure 'logo.ico' is in your /public folder
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      {/* The <head> tag is now automatically generated by Next.js from the metadata object above */}
      <body>
        <ThemeRegistry>
          <Navbar />
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
