steps:
# 1. Build and push the Backend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:$COMMIT_SHA', './backend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:$COMMIT_SHA']

# 2. Build and push the Frontend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:$COMMIT_SHA', './frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:$COMMIT_SHA']

# 3. Build and push the LLM-Service image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-service:$COMMIT_SHA', './llm-service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-service:$COMMIT_SHA']

# 4. Update the Kubernetes deployments with the new image version
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - 'study-buddy-cluster'
    - '--zone=europe-west1-b' # Your cluster's zone
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/backend-deployment'
    - 'backend=europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:$COMMIT_SHA'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/frontend-deployment'
    - 'frontend=europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:$COMMIT_SHA'
# Add a similar step for the llm-service deployment

images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:$COMMIT_SHA'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:$COMMIT_SHA'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-service:$COMMIT_SHA'

