options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 0. Fetch backend secrets from Secret Manager and write to backend/.env
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud secrets versions access 1 --secret="backend" > backend/.env

# 1a. Build the Backend image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--cache-from' # Use the latest image as cache source
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:latest'
    - '-t'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:$COMMIT_SHA'
    - './backend' # The build context directory
# 1b. Push the Backend image with commit and latest tags
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:$COMMIT_SHA', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:latest']

# 2a. Build the Frontend image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--cache-from' # Use the latest image as cache source
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:latest'
    - '-t'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:$COMMIT_SHA'
    - './frontend' # The build context directory
# 2b. Push the Frontend image with commit and latest tags
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:$COMMIT_SHA', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:latest']

# 3a. Build and push the LLM-Service worker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--cache-from' # Use the latest image as cache source
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-worker:latest'
    - '-t'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-worker:$COMMIT_SHA'
    - '-f' # This flag specifies the Dockerfile to use
    - 'llm-service/Dockerfile.cuda'
    - './llm-service' # The build context directory
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-worker:$COMMIT_SHA']

# 3b. Build and push the LLM-Service api image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--cache-from' # Use the latest image as cache source
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-api:latest'
    - '-t'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-api:$COMMIT_SHA'
    - '-f' # This flag specifies the Dockerfile to use
    - 'llm-service/Dockerfile'
    - './llm-service' # The build context directory
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-api:$COMMIT_SHA']

# 4a. Tag the 3a image as 'latest' and push them for automatic deployment
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-worker:$COMMIT_SHA', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-worker:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-worker:latest']

# 4b. Tag the 3b image as 'latest' and push it for automatic deployment
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-api:$COMMIT_SHA', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-api:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-api:latest']

# # 4. Trigger Cloud Deploy pipeline (commented out since we are switching to Terraform)
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'gcloud'
#   args:
#     - 'deploy'
#     - 'releases'
#     - 'create'
#     - 'release-$SHORT_SHA'
#     - '--delivery-pipeline=study-buddy-pipeline'
#     - '--region=europe-west1'
#     - '--images=backend=europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:$COMMIT_SHA,frontend=europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:$COMMIT_SHA,llm-service=europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-service:$COMMIT_SHA'

images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:$COMMIT_SHA'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/backend:latest'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:$COMMIT_SHA'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/frontend:latest'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-worker:$COMMIT_SHA'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-worker:latest'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-api:$COMMIT_SHA'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/study-buddy-repo/llm-api:latest'