apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: study-buddy-pipeline
description: Deploy to study-buddy-cluster
serialPipeline:
  stages:
    - targetId: study-buddy-target
      profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: study-buddy-target
description: GKE target for study buddy app
gke:
  cluster: projects/gruppo-11/locations/europe-west1/clusters/study-buddy-cluster
