services:
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rd:
    image: redis:alpine
    command: redis-server --appendonly yes --appendfsync everysec
    volumes:
      - rd1-data:/data
    networks:
      - app-network
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      sh -c "python /app/manage.py migrate &&
            python /app/manage.py init_admin &&
            daphne -b 0.0.0.0 -p 8000 study.asgi:application"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      sh -c "celery -A study worker -l info"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web
      - rd
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles/
      - media_volume:/app/media/
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

volumes:
  pgdata:
    external: true
  static_volume:
    external: true
  media_volume:
    external: true
  rd1-data:
    external: true

networks:
  app-network:
    external: true
