services:
  db:
    image: postgis/postgis:14-3.1
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      sh -c "python /app/manage.py migrate &&
            python /app/manage.py init_admin &&
            gunicorn study.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles/
      - media_volume:/app/media/
      #- ./resc/staticfiles:/app/resc/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

volumes:
  pgdata:
    external: true
  static_volume:
    external: true
  media_volume:
    external: true

networks:
  app-network:
    external: true
