apiVersion: batch/v1
kind: Job
metadata:
  name: k6-stress-test
  namespace: stress-test
spec:
  template:
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          command: ["k6", "run", "/scripts/k6-script.js"]
          volumeMounts:
            - name: k6-script-volume
              mountPath: /scripts
          env:
            - name: BASE_URL
              value: "https://study-buddy.duckdns.org" 
      restartPolicy: Never
      volumes:
        - name: k6-script-volume
          configMap:
            name: k6-script
  backoffLimit: 0
