# Generated by Django 5.2.1 on 2025-07-14 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='topic',
            name='unique_user_topic_title',
        ),
        migrations.AddField(
            model_name='topic',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('archived', False)), fields=('user', 'title'), name='unique_user_topic_title_if_not_archived'),
        ),
    ]
