apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2 # Start with 2 replicas for availability
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: europe-west1-docker.pkg.dev/gruppo-11/study-buddy-repo/backend:latest
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_URL
            value: "postgresql://your_db_user:your_db_password@postgres-service:5432/your_db_name" # Replace credentials
          - name: MISTRAL_API_KEY
            value: "your_mistral_api_key" # Consider using Kubernetes Secrets for this
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP # Only expose internally
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
