# name: Terraform CI

# on:
#   push:
#     paths:
#       - 'frontend/**'
#       - 'terraform/**'
#   pull_request:
#     paths:
#       - 'frontend/**'
#       - 'terraform/**'

# jobs:
#   terraform:
#     name: Build Docker, Push Image, Plan & Deploy
#     runs-on: ubuntu-latest

#     defaults:
#       run:
#         working-directory: terraform

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: Authenticate to Google Cloud
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

#       - name: Configure Docker for Artifact Registry
#         run: |
#           gcloud auth configure-docker europe-west1-docker.pkg.dev

#       - name: Build Docker Image for Frontend
#         run: |
#           docker build -t europe-west1-docker.pkg.dev/gruppo-11/frontend/study-buddy-frontend:latest ../frontend

#       - name: Push Docker Image to Artifact Registry
#         run: |
#           docker push europe-west1-docker.pkg.dev/gruppo-11/frontend/study-buddy-frontend:latest

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.6.6

#       - name: Terraform Format Check
#         run: terraform fmt -check -recursive

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Validate
#         run: terraform validate

#       - name: Terraform Plan
#         run: terraform plan -var-file="terraform.tfvars"

#       - name: Run tfsec (Security Scan)
#         uses: aquasecurity/tfsec-action@v1.0.3
#         with:
#           working-directory: terraform

#       - name: Terraform Apply
#         if: github.ref == 'refs/heads/main'
#         run: terraform apply -auto-approve -var-file="terraform.tfvars"


name: Terraform CI

on:
  push:
    paths:
      - 'frontend/**'
      - 'terraform/**'
  pull_request:
    paths:
      - 'frontend/**'
      - 'terraform/**'

jobs:
  terraform:
    name: Build Docker, Push Image, Plan & Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Set image tag
        id: tag
        run: echo "IMAGE_TAG=sha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image for Frontend
        run: |
          docker build -t europe-west1-docker.pkg.dev/gruppo-11/frontend/study-buddy-frontend:${{ env.IMAGE_TAG }} ../frontend

      - name: Push Docker Image to Artifact Registry
        run: |
          docker push europe-west1-docker.pkg.dev/gruppo-11/frontend/study-buddy-frontend:${{ env.IMAGE_TAG }}

      - name: Write terraform.tfvars dynamically
        run: |
          echo 'image = "europe-west1-docker.pkg.dev/gruppo-11/frontend/study-buddy-frontend:${{ env.IMAGE_TAG }}"' > terraform/terraform.tfvars

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Run tfsec (Security Scan)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working-directory: terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"


        
